homework 2
ShellKhan/Basic_JavaScript pull request #2
Opened 2021-03-26 13:19 UTC by ShellKhan

2021-03-27 15:09 UTC, Om1X requested changes

2021-03-27 15:09 UTC, Om1X commented on homework.js
> +    } else if ((a < 0) || (b < 0)) {
некорректное условие. это условие будет выполняться в случаях если a отрицательное и b абсолютно любое число (отрицательное, положительное или равное нулю) или если b отрицательное и a любое.

2021-03-27 17:07 UTC, ShellKhan commented on homework.js
> +    } else if ((a < 0) || (b < 0)) {
я всё это учел. случаи, когда оба отрицательные, мы отобрали предыдущим условием. а 0 по условию задачи можно считать положительным числом. так что отберутся только ситуации, когда у a и b разные знаки.

2021-03-31 11:39 UTC, Om1X commented on homework.js
> +    } else if ((a < 0) || (b < 0)) {
Все верно, совсем намылил глаз на предыдущих ДЗ.

2021-03-31 19:16 UTC, merged